=== HebaMostafa123/Tic-Tac-Toe/XML/src/xml/newemptyDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->

<!ELEMENT library (librarian, book+)>
<!ATTLIST library location CDATA #REQUIRED description CDATA #REQUIRED> 
<!ELEMENT librarian (#PCDATA) >
<!ELEMENT book (preface, part+)>
<!ATTLIST book title CDATA #REQUIRED isbn CDATA #REQUIRED author CDATA #REQUIRED>
<!ELEMENT preface (#PCDATA) >
<!ELEMENT part (chapter)+ >
<!ATTLIST part title CDATA #REQUIRED>
<!ELEMENT chapter (summary, section+)>
<!ATTLIST chapter title CDATA #REQUIRED>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT section (#PCDATA)>

=== HebaMostafa123/Tic-Tac-Toe/XML/src/xml/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE library SYSTEM "newemptyDTD.dtd"> 
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--//<library desc= SYSTEM>-->

<library location="64-tahrer,Giza,EGYPT" description="containe programming books">
    
    <librarian></librarian>
    
    <book title="C++" isbn="b1" author="dr.C">
        
        <preface></preface>
        
        <part title="p1">
            
            <chapter title="introduction">
                <summary></summary>
                <section>
                    <![CDATA[ 
                       this section will talk about ..... 
                    ]]>
                </section>
                <section></section>
            </chapter>
            
            <chapter title="hellow world">
                
                <summary></summary>
                <section>
                    <![CDATA[ 
                       this section will talk about ..... 
                    ]]>
                </section>
                
                <section></section>
            </chapter>
            
        </part>
        
        <part title="p1">
            
            <chapter title="introduction">
                <summary></summary>
                <section>
                    <![CDATA[ 
                       this section will talk about ..... 
                    ]]>
                </section>
                <section></section>
            </chapter>
            
            <chapter title="hellow world">
                <summary></summary>
                <section>
                    <![CDATA[ 
                       this section will talk about ..... 
                    ]]>
                </section>
                
                <section></section>
            </chapter>
            
        </part>
        

        
        
    </book>
    
    <book title="Java" isbn="b2" author="dr.Java">

        <preface></preface>

        <part title="p1">
            
            <chapter title="introduction" >
                <summary></summary>
                <section>
                    <![CDATA[ 
                       this section will talk about ..... 
                    ]]>
                </section>
                <section>asdfasdf</section>
            </chapter>
            
            <chapter title="hellow world">
                <summary></summary>
                <section>
                    <![CDATA[ 
                       this section will talk about ..... 
                       < > & ' "
                    ]]>
                </section>
                
                <section></section>
            </chapter>
            
        </part>
        
        <part title="p1">
            
            <chapter title="introduction">
                <summary></summary>
                <section>
                    <![CDATA[ 
                       this section will talk about ..... 
                    ]]>
                </section>
                <section></section>
            </chapter>
            
            <chapter title="hellow world">
                <summary></summary>
                <section>
                    <![CDATA[ 
                       this section will talk about ..... 
                    ]]>
                </section>
                
                <section></section>
            </chapter>
            
        </part>
                
        
    </book>
  
</library>
